apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m04d5yeg4-go
  janus-idp.io/tekton: m04d5yeg4-go
  backstage.io/kubernetes-id: m04d5yeg4-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: m04d5yeg4-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
